language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - mkdir -p ~/.composer
  - echo '{"config":{"github-oauth":{"github.com":"9ce09134a109ffe063cd9e865b8251eeb99ba5a2"}}}' > ~/.composer/config.json
  - composer self-update
  - composer update --prefer-source --dev --no-interaction

script: 
  - vendor/bin/phpunit